using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo.Partial
{
    // supposed its auto generated by EF Core
    internal partial class Employee
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public decimal? Salary { get; set; }
        public int? Age { get; set; }

        public partial void Test();
        
        // will be removed when the class is regenerated by EF Core
        //public void Display()
        //{
        //    Console.WriteLine($"Id: {Id}, Name: {Name}, Age: {Age}");
        //}
    }
}
